// Auto-generated by scripts/write-version.mjs during builds.
export const APP_VERSION = "177.8.260808";
export const APP_BUILD_ID = "local-20260809000330";
export const APP_BUILT_AT = "2026-08-09T00:03:30.165Z";
