// Auto-generated by scripts/write-version.mjs during builds.
export const APP_VERSION = "1.0.18";
export const APP_BUILD_ID = "local-20260616010949";
export const APP_BUILT_AT = "2026-06-16T01:09:49.113Z";
