// Auto-generated by scripts/write-version.mjs during builds.
export const APP_VERSION = "1.83.2";
export const APP_BUILD_ID = "local-20260706010121";
export const APP_BUILT_AT = "2026-07-06T01:01:21.098Z";
