import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const root = process.cwd();
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

// Today's date in US/Eastern (the app's canonical tz) as YYMMDD. DST-safe via IANA tz.
function easternYYMMDD(d = new Date()) {
  const parts = new Intl.DateTimeFormat('en-US', {
    timeZone: 'America/New_York', year: '2-digit', month: '2-digit', day: '2-digit',
  }).formatToParts(d);
  const g = (t) => parts.find((p) => p.type === t).value;
  return `${g('year')}${g('month')}${g('day')}`;
}

// User-facing version. New scheme FEATURE.EDIT.YYMMDD: the date segment is AUTO-STAMPED here to today's
// Eastern date, so it's always correct and never hand-typed. Only FEATURE.EDIT is maintained in
// package.json. A 6-digit third segment marks the new scheme; the legacy 1.MINOR.PATCH form is left as-is.
const rawVersion = String(process.env.NEXT_PUBLIC_APP_VERSION || pkg.version || '1.0.0');
let appVersion = rawVersion;
const m = rawVersion.match(/^(\d+)\.(\d+)\.(\d+)$/);
if (m && m[3].length === 6) {
  appVersion = `${m[1]}.${m[2]}.${easternYYMMDD()}`;
}

// Machine/support build id. Useful for debugging, but not the primary label shown to users.
const buildId = String(
  process.env.VERCEL_GIT_COMMIT_SHA ||
  process.env.VERCEL_GIT_COMMIT_REF ||
  `local-${new Date().toISOString().replace(/[-:.TZ]/g, '').slice(0, 14)}`
).slice(0, 40);

const builtAt = new Date().toISOString();

function write(path, content) {
  const full = join(root, path);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content);
}

write('public/app-version.json', `${JSON.stringify({ version: appVersion, buildId, builtAt }, null, 2)}\n`);
write(
  'lib/app-version.ts',
  `// Auto-generated by scripts/write-version.mjs during builds.\n` +
  `export const APP_VERSION = ${JSON.stringify(appVersion)};\n` +
  `export const APP_BUILD_ID = ${JSON.stringify(buildId)};\n` +
  `export const APP_BUILT_AT = ${JSON.stringify(builtAt)};\n`
);

const swPath = join(root, 'public/sw.js');
let sw = readFileSync(swPath, 'utf8');
const swVersion = `${appVersion}-${buildId}`;
const replacement = `const SW_VERSION = ${JSON.stringify(swVersion)};\nconst CACHE = \`bnn-shell-\${SW_VERSION}\`;`;
if (/const SW_VERSION = [^;]+;\s*\nconst CACHE = `bnn-shell-\$\{SW_VERSION\}`;/.test(sw)) {
  sw = sw.replace(/const SW_VERSION = [^;]+;\s*\nconst CACHE = `bnn-shell-\$\{SW_VERSION\}`;/, replacement);
} else if (/const CACHE = ["']bnn-shell-[^"']+["'];/.test(sw)) {
  sw = sw.replace(/const CACHE = ["']bnn-shell-[^"']+["'];/, replacement);
} else {
  throw new Error('Could not find CACHE declaration in public/sw.js');
}
writeFileSync(swPath, sw);

console.log(`Wrote app version ${appVersion} (${buildId})`);
