import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const root = process.cwd();
const rawVersion =
  process.env.NEXT_PUBLIC_APP_VERSION ||
  process.env.VERCEL_GIT_COMMIT_SHA ||
  process.env.VERCEL_GIT_COMMIT_REF ||
  `local-${new Date().toISOString().replace(/[-:.TZ]/g, '').slice(0, 14)}`;

const version = String(rawVersion).slice(0, 40);
const builtAt = new Date().toISOString();

function write(path, content) {
  const full = join(root, path);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content);
}

write('public/app-version.json', `${JSON.stringify({ version, builtAt }, null, 2)}\n`);
write('lib/app-version.ts', `// Auto-generated by scripts/write-version.mjs during builds.\nexport const APP_VERSION = ${JSON.stringify(version)};\nexport const APP_BUILT_AT = ${JSON.stringify(builtAt)};\n`);

const swPath = join(root, 'public/sw.js');
let sw = readFileSync(swPath, 'utf8');
const replacement = `const SW_VERSION = ${JSON.stringify(version)};\nconst CACHE = \`bnn-shell-\${SW_VERSION}\`;`;
if (/const SW_VERSION = [^;]+;\s*\nconst CACHE = `bnn-shell-\$\{SW_VERSION\}`;/.test(sw)) {
  sw = sw.replace(/const SW_VERSION = [^;]+;\s*\nconst CACHE = `bnn-shell-\$\{SW_VERSION\}`;/, replacement);
} else if (/const CACHE = ["']bnn-shell-[^"']+["'];/.test(sw)) {
  sw = sw.replace(/const CACHE = ["']bnn-shell-[^"']+["'];/, replacement);
} else {
  throw new Error('Could not find CACHE declaration in public/sw.js');
}
writeFileSync(swPath, sw);

console.log(`Wrote app version ${version}`);
